version: '3'

services:
  freeipa:
    image: freeipa/freeipa-server:rocky-9 # 使用FreeIPA Server的最新映像
    hostname: ipa.infowize.com # 容器主機名稱為ipa.infowize.com
    environment: # 定義容器的環境變數
      IPA_SERVER_IP: 192.168.10.139 # FreeIPA伺服器的IP位址
      IPA_SERVER_HOSTNAME: ipa.infowize.com # FreeIPA伺服器的主機名稱
      IPA_DOMAIN: infowize.com # FreeIPA網域名稱
      IPA_ADMIN_PASSWORD: P@ssw0rd! # FreeIPA管理員密碼
      IPA_REPLICA_FILE: /data/ipa-replica-info # IPA複本資訊檔案路徑
    volumes: # 定義容器的卷
      - ./ipa-data:/data # 永久儲存FreeIPA伺服器的資料
    ports: # 定義容器所開放的埠口
      - "9080:80"
      - "9443:443"
      - "88:88"
      - "389:389"
      - "636:636"
    command: "/usr/sbin/init" # 容器啟動後運行的指令

volumes:
  ipa-data: # 定義容器的卷，用於永久儲存FreeIPA伺服器的資料
  
### ubuntu 22 未啟動
