version: '3'

services:
  mysql:
    image: mariadb
    container_name: librenms_db
    volumes:
      - ./librenms_db:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=1qaz@WSX
      - MYSQL_DATABASE=librenms
      - TZ=Asia/Taipei
    restart: always

  librenms:
    image: seti/librenms
    container_name: librenms
    hostname: librenms
    volumes: ## /config/config.php
      - ./librenms_data:/data   
    ports:
      - 8080:80
      - 514:514/tcp
      - 514:514/udp
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=root
      - DB_PASS=1qaz@WSX
      - TZ=Asia/Taipei
      - POLLER=16  ## 4*CPU
      - SERVICES_ENABLED=1
      - UPDATE_CHANNEL=master
      - SYSLOG_ENABLED=1
    restart: always

## login < librenms | librenms >  a few moment later 
## git clone https://github.com/setiseta/docker-librenms.git

  mongo:
    container_name: mongodb
    image: mongo:3
    restart: always
    volumes:
      - ./graylog_db:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    container_name: elasticsearch
    restart: always
    volumes:
      - ./graylog_es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment: ## mem 最少 512M
      - TZ=Aisa/Taipei
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - http.cors.allow-origin=*
      - http.cors.enabled=true
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'  
  graylog: 
    image: graylog/graylog:4.1
    container_name: graylog
    restart: always
    volumes:  
      - ./graylog_journal:/usr/share/graylog/data/journal
      - ./graylog_config:/usr/share/graylog/config
    ports:
      - 9090:9000
      - 12201:12201/udp  ## log port <GELF UDP>set up inputs
    environment:  ## <host IP >
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.10.132:9090/
    depends_on:
      - mongo
      - elasticsearch
    links:
      - mongo
      - elasticsearch

## wget https://github.com/Graylog2/graylog-docker/blob/4.1/config/graylog.conf  <put graylog.conf in ./config>
## chmod 777 es_data
## chmod 777 graylog_journal
## admin | admin

## nano /libre_data/config/config.php  ## when stack stop
##$config['graylog']['server']   = 'http://192.168.10.132';
##$config['graylog']['port']     = 9090;
##$config['graylog']['username'] = 'admin'; 
##$config['graylog']['password'] = 'admin';
##$config['graylog']['version']  = '4.1';
##$config['graylog']['timezone'] = 'Asia/Taipei';



