version: "3.8"
services:  
  freeipa:
    image: freeipa/freeipa-server:centos-8-stream
    hostname: ipa
    domainname: ipa.infowize.com.tw
    container_name: freeipa-dev
    ports:
      - 80:80
      - 443:443
      - 389:389
      - 636:636
      - 88:88
      - 464:464
      - 88:88/udp
      - 464:464/udp
      - 123:123/udp
    dns:
      - 168.95.192.1
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      IPA_SERVER_HOSTNAME: ipa.infowize.com.tw
      IPA_SERVER_IP: 192.168.10.124
      TZ: "Asia/Taipei"
    command:
      - -U
      - --domain=ipa.infowize.com.tw
      - --realm=ipa.infowize.com.tw
      - --admin-password=password
      - --http-pin=password
      - --dirsrv-pin=password
      - --ds-password=password
      - --no-dnssec-validation
      - --no-host-dns
      - --setup-dns
      - --auto-forwarders
      - --allow-zone-overlap
      - --unattended
    cap_add:
      - SYS_TIME
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /opt/ipa/data:/data
      - /opt/ipa/logs:/var/logs
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    labels:
      - dev