version: '3.7'
services:
  freeipa:
    image: freeipa/freeipa-server:centos-8-stream
    restart: unless-stopped
    container_name : IPA
    hostname: U20d127
    environment:
      IPA_SERVER_HOSTNAME: U20d127
      TZ: "Asia/Taipei"
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./freeipavol:/data
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    command:
      - -U
      - --domain=wp.infowize.com.tw
      - --realm=wp.infowize.com.tw
      - --http-pin=password
      - --dirsrv-pin=password
      - --ds-password=password
      - --admin-password=password
      - --no-host-dns
      - --unattended
    ports:
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "88:88/udp"
      - "464:464/udp"
      - "123:123/udp"
      - "7389:7389"
      - "9443:9443"
      - "9444:9444"
      - "9445:9445"

volumes:
  freeipavol: