version: '3.3'

services:
  openldap:
    container_name: openldap
    image: osixia/openldap:1.5.0
    restart: always
    environment: 
      TZ: Asia/Taipei
      LDAP_ADMIN_PASSWORD: "password"
      LDAP_ORGANISATION: "infowize_office"
      LDAP_DOMAIN: "infowize.com.tw"
    volumes:
      - /opt/lapd/database:/var/lib/ldap
      - /opt/lapd/config:/etc/ldap/slapd.d
#      - /opt/ldap/backup:/data/backup
#      - /opt/ldap/certs:/assets/slapd/certs
    ports:
      - 389:389
      - 636:636

  phpldapadmin:
    container_name: openldap-WUI
    image: osixia/phpldapadmin:0.9.0
    restart: always
    environment:
      TZ: Asia/Taipei
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    ports:
      - 6443:443     
# ldapsearch -x -H ldap://192.168.10.127 -b "dc=infowize,dc=com,dc=tw" -D "cn=admin,dc=infowize,dc=com,dc=tw" -w password
#https://www.antio.top/pages/a3a305/#%E8%83%8C%E6%99%AF